name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - name: Build
        run: |
          npm i
          npm run prod
      - name: Upload static build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
  percy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download static build
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "public/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  deploy:
    needs: [build, percy]
    runs-on: ubuntu-latest
    steps:
      - name: Download static build
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - uses: chrislennon/action-aws-cli@1.1
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then flags="--dryrun"; else flags=""; fi
          aws s3 sync public s3://www.athal7.com $flags
          aws s3 sync public s3://www.rebeccamiller.me $flags
