name: Build & Deploy

on:
  push:
    branches:
      - andrew

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: build
        run: |
          npm i
          npm run prod
      - uses: chrislennon/action-aws-cli@1.1
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 sync app/assets/images s3://www.athal7.com/images
          aws s3 sync public s3://www.athal7.com
