name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.0
      - name: Build
        run: |
          npm i
          npm run build
      - name: Upload static build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
  percy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download static build
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "public/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  deploy:
    needs: [build, percy]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download static build
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        run: |
          aws s3 sync public s3://www.athal7.com
          aws s3 sync public s3://www.rebeccamiller.me
